kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-network-cluster-reader
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ibm-network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
