# ibm-provisioning group binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-provisioning-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ibm-provisioning
---
# cluster admin binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ibm-cluster-admins
---
# sre role
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-sre-editor
rules:
  - verbs: ["*"]
    apiGroups: [""]
    resources: ["pods", "pods/exec"]
  - verbs: ["*"]
    apiGroups: [""]
    resources: ["secrets"]
  - verbs: ["*"]
    apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale", "statefulsets"]
  - verbs: ["create", "update", "patch", "get", "list"]
    apiGroups: ["route.openshift.io"]
    resources: ["routes"]
  - verbs: ["update", "patch", "get", "list"]
    apiGroups: ["apps.mas.ibm.com"]
    resources: ["*"]
  - verbs: ["update", "patch", "get", "list"]
    apiGroups: ["config.mas.ibm.com"]
    resources: ["*"]
  - verbs: ["*"]
    apiGroups: ["cert-manager.io"]
    resources: ["*"]
  - verbs: ["*"]
    apiGroups: ["acme.cert-manager.io"]
    resources: ["*"]
  - verbs: ["get", "list", "watch", "update", "patch"]
    apiGroups: ["operators.coreos.com"]
    resources: ["clusterserviceversions", "installplans", "subscriptions"]
---
# sre cluster reader binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-sre-cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ibm-sre
---
# sre editor binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-sre-editor-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-sre-editor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ibm-sre
---
# dba role
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-dba-cluster-role
rules:
  - verbs: ["*"]
    apiGroups: [""]
    resources: ["pods", "pods/exec", "services"]
  - verbs: ["*"]
    apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
  - verbs: ["get", "list", "watch"]
    apiGroups: [""]
    resources: ["secrets"]
  - verbs: ["*"]
    apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
  - verbs: ["update", "patch", "get", "list"]
    apiGroups: ["db2u.databases.ibm.com"]
    resources: ["*"]
  - verbs: ["update", "patch", "get", "list"]
    apiGroups: ["datarefinery.cpd.ibm.com"]
    resources: ["*"]
  - verbs: ["update", "patch", "get", "list"]
    apiGroups: ["databases.cpd.ibm.com"]
    resources: ["*"]
---
# dba cluster reader binding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-reader
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ibm-dba
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
---
# dba edit binding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-dba-edit-rb
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ibm-dba
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-dba-cluster-role
---
# network role
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-network-cluster-role
rules:
  - verbs: ["*"]
    apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
  - verbs: ["*"]
    apiGroups: ["network.openshift.io"]
    resources: ["egressnetworkpolicies"]
  - verbs: ["*"]
    apiGroups: ["operator.openshift.io"]
    resources: ["ingresscontrollers"]
  - verbs: ["get"]
    apiGroups: ["operator.openshift.io"]
    resources: ["dnses"]
---
# network binding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-network-rb.yaml
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ibm-network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-network-cluster-role
---
# network cluster reader binding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-network-cluster-reader
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ibm-network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
---
# ibm-sre-automation cluster admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-sre-automation-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ibm-sre-automation
