apiVersion: v2
name: rbac
description: RBAC
type: application
version: 1.0.0

dependencies:
- name: junitreporter
  version: 1.0.0
  repository: "file://../../sub-charts/junitreporter/"
  condition: junitreporter.devops_mongo_uri != ""